import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '@/widgets/Header/ui/header';
import localFont from 'next/font/local';

const dihjauti = localFont({
  src: './fonts/dihjauti.regular.otf', // проверь расширение своего файла!
  variable: '--font-dihjauti', // создаем CSS-переменную
});
const fixelDisplay = localFont({
  src: './fonts/fixeldisplaylight.woff2', // проверь расширение своего файла!
  variable: '--font-fixelDisplay',
});
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fixelDisplay.variable} ${dihjauti.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 1. Вставляем Header сверху */}
        <Header />

        {/* 2. Контент страницы оборачиваем в <main>, чтобы браузер понимал иерархию */}
        <main className="avltu_container">{children}</main>
      </body>
    </html>
  );
}
